modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="lightland"
version="6.4.7" #mandatory
displayName="LightLand RPG" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.lightland]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
[[dependencies.lightland]]
    modId="appleskin"
    mandatory=false
    versionRange="[2.3.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.lightland]]
    modId="create"
    mandatory=true
    versionRange="[0.4.1,)"
    ordering="AFTER"
[[dependencies.lightland]]
    modId="jei"
    mandatory=true
    versionRange="[9.7,)"
    side="CLIENT"